Add support for intellij
sindresorhus/env-editor pull request #2
Opened 2017-05-06 20:51 UTC by SimenB

2017-05-06 21:11 UTC, sindresorhus requested changes

2017-05-06 21:11 UTC, sindresorhus commented on index.js
> +	paths: [],
Can you add the path to the binary?

2017-05-06 21:11 UTC, sindresorhus commented on readme.md
> +- IntelliJ
Place it at the bottom. Same with the other places.

2017-05-06 21:11 UTC, sindresorhus commented on index.js
> +	keywords: []
Keywords could be: idea, java, jetbrains, ide

2017-05-06 21:11 UTC, sindresorhus commented on index.js
> +	name: 'IntelliJ',
Seems the official name is: IntelliJ IDEA

2017-05-06 21:20 UTC, SimenB commented on index.js
> +	paths: [],
The `idea` binary, or the app?
The app itself varies with version (mine is now `RUN_PATH = u'/Users/simen/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/171.4424.14/IntelliJ IDEA 2017.1 EAP.app'`).

The binary is generated by hand in the IDE, with a user-defined path. This is the default:

![image](https://cloud.githubusercontent.com/assets/1404810/25775997/6dcec332-32b2-11e7-83c4-26e57df3f86b.png)

Should I use that?

This is the exact same as webstorm, btw. WebStorm is just the JS parts of intellij, so changes to one here should change the other

2017-05-06 21:20 UTC, SimenB commented on index.js
> +	keywords: []
Added 😄

2017-05-06 21:21 UTC, SimenB commented on readme.md
> +- IntelliJ
Done

2017-05-07 05:46 UTC, sindresorhus commented on index.js
> +	paths: [],
Nah, it's fine. That's a standard location to look.

2017-05-07 05:47 UTC, sindresorhus approved these changes

2017-05-07 05:47 UTC, merged

2017-05-07 05:53 UTC, sindresorhus commented
Thanks :)